apiVersion: v1
kind: Service
metadata:
  name: "app-{{ .Values.Environment }}-service"
  namespace: "{{ .Values.Namespace }}"
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.Service.Port }}
      protocol: TCP
  selector:
    app: "{{ .Values.Environment }}"
