---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/intertecio/kubernetes-interview-task-Dev7'
    targetRevision: HEAD
    path: infrastructure/helm/app
    helm:
      values: |
        Environment: green
        ReplicaCount: 3
        Image:
          Repository: 402022866377.dkr.ecr.eu-central-1.amazonaws.com/node-demo-app
          Tag: "green"
          PullPolicy: IfNotPresent
        Service:
          Type: ClusterIP
          Port: 3000

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true