---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alb-controller-leader-election-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["aws-load-balancer-controller-leader"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["aws-load-balancer-controller-leader"]
    verbs: ["get", "update", "patch"]
