---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alb-controller-leader-election-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alb-controller-leader-election-role
subjects:
  - kind: ServiceAccount
    name: alb-controller
    namespace: kube-system
