---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alb-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: ${AWS_IAM_ROLE_ARN}
automountServiceAccountToken: true
